Update tester-definition.yml

diff --git a/tester-definition.yml b/tester-definition.yml
--- a/tester-definition.yml
+++ b/tester-definition.yml
@@ -10,7 +10,18 @@ sections:
           - name: "cargo init"
             slug: "cargo-init" # This must be unique for this entire course
             optional: false
-            cmd: "cargo run"
+            cmd: |
+              output=$(cargo run 2>&1)
+              status=$?
+              if [ $status -ne 0 ]; then
+                echo "Test Failed: The program did not exit successfully."
+                exit 1
+              elif [[ $output == *"Hello, world!"* ]] && [[ $output != *"panic"* ]]; then
+                echo "Congrats! You've successfully initialized your Rust Project."
+              else
+                echo "Looks like `cargo run` is failing to execute. Maybe there's a bug in your code?"
+                exit 1
+              fi
             message_on_fail: "Looks like `cargo run` is failing to execute. Maybe there's a bug in your code?"
             message_on_success: "Congrats! You've successfully initialized your Rust Project."
           - name: "foo"
